Add v3 signature to a packet
aronsky/esphome-components pull request #9
Opened 2024-02-26 18:45 UTC by flicker581

V3 protocol require packet signatures before CRC and "whitening".

Current LampSmart Pro does not support sending commands without this signature, so, I suppose it is harmless.

2024-02-26 22:51 UTC, oxcid3 commented
Watching this and testing on my light. Not currently working but very excited that you're trying to sort. Thanks 🤞🏻

2024-02-27 05:03 UTC, aronsky requested changes
A couple of notes:

1. We'll need to verify that changing that field from 0 to the signature value does not break lights that don't use the signature (e.g., the lights I use :) ). I can help with that.
2. If 1 fails, we'll need to make the changes in this PR optional, i.e. - make the use of the signature configurable.
3. I don't want to add an AES implementation to the source tree unless absolutely necessary (it doesn't even have a license at the top - excuse my bluntness, but is this code yours?). I prefer to use libraries where possible. It seems that ESP32 supports hardware AES encryption/decryption - why not use it? See an example here: https://github.com/ffosilva/AES32.

2024-02-27 05:04 UTC, aronsky commented on components/lampsmart_pro_light/lampsmart_pro_light.cpp
> +  AES_ECB_encrypt(&aes_ctx, aes_buf);
This needs to be in a separate function.

2024-02-27 14:26 UTC, flicker581 commented
1. LampSmartPro 1.2.9 sends only v3 messages (i.e. with the signature). This makes me feel that the change is backward compatible. I have no ways to test, because I do not own any of these lamps. I have checked only that:
- the signature generated by the code is passing the same check as LampSmartPro's signature.
- my friend's lamp is working with this code. 
2. Ok. Unfortunately, base code have no provisions for pluggable algorithms.
3. AES code is from https://github.com/kokke/tiny-AES-c, where it is published as "public domain". Now I have replaced it with mbedtls, which comes in arduino-espressif32. Have no idea how stable this dependency is.

Feel free to use my code as you wish, integrate it some way or drop it. I personally have no special interest in it. Sorry.

@oxcid3 
So, if this does not work for you (and you are sure doing thing right), your lamp needs older algo. Tried lampify yet?

2024-02-27 15:11 UTC, aronsky commented
@flicker581 - thanks for the changes! I'll test it as soon as I get the chance (to verify that it's backward-compatible), and get back to you.

2024-03-17 07:34 UTC, aronsky approved these changes

2024-03-17 07:36 UTC, aronsky commented
Thanks for the changes. I didn't get a chance to test them out (as I switched to a different LED driver that works with a different app). I'm merging this - hopefully it works for everyone. In any case, for now, the version without the signature remains available in the refactored code - and in the future, I'll add support to make the signing optional.

2024-03-17 07:36 UTC, merged